# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCAProtect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCAProtect

  pod 'Alamofire', '~> 4.0'
  pod 'SDWebImage'
  pod 'JVFloatLabeledTextField'

  target 'MCAProtectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MCAProtectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
