# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCAProtect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCAProtect

  pod 'Alamofire', '~> 4.0'
  pod 'SDWebImage'
  pod 'JVFloatLabeledTextField'
  pod 'iOS-Slide-Menu', '~> 1.5'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'SDWebImage', '~> 3.8'
  target 'MCAProtectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MCAProtectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
